services:
  vitrina_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitrina-web
    container_name: vitrina-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/db:/app/db
      - ./backend/.prospector.yaml:/app/.prospector.yaml
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
      - ./backend/manage.py:/app/manage.py
      - ./backend/showcase:/app/showcase
      - ./backend/model:/app/model
      - ./backend/marketplace:/app/marketplace
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:17
    container_name: vitrina-postgres
    ports:
      - 5432:5432 # TODO: CHECK.
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: showcase_db
      POSTGRES_USER: showcase_user
      POSTGRES_PASSWORD: showcase_pass

volumes:
  data:
    driver: local
