# Generated by Django 5.2.4 on 2025-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DigitalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("file_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("discount_percentage", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="CLP price in pesos (e.g. 35700 = $35.700)"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_online", models.BooleanField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("video_call_url", models.URLField(blank=True)),
            ],
        ),
    ]
