# Generated by Django 5.2.4 on 2025-07-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_create_Customer"),
        ("model", "0001_create_Event_DigContent_Discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("normal_price", models.PositiveIntegerField()),
                ("final_price", models.PositiveIntegerField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("failed", "Failed")],
                        default="failed",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="model.digitalcontent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_downloads",
                        to="marketplace.customer",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="model.discountcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("normal_price", models.PositiveIntegerField()),
                ("final_price", models.PositiveIntegerField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("failed", "Failed")],
                        default="failed",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to="marketplace.customer",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="model.discountcode",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="model.event",
                    ),
                ),
            ],
        ),
    ]
