# Generated by Django 5.2.4 on 2025-07-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_create_ContentDownload_EventRegistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="password",
        ),
    ]
